version: "3.8"

services:
  db:
    image: postgres:15-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5455:5432
    networks:
      - kc-network

  kc1:
    build:
      context: ${PWD}/keycloak/
      dockerfile: Dockerfile
    container_name: kc1
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - kc-network
    volumes:
      - kc-log:/var/log/keycloak

  kc2:
    build:
      context: ${PWD}/keycloak/
      dockerfile: Dockerfile
    container_name: kc2
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - kc-network
    volumes:
      - kc-log:/var/log/keycloak

  haproxy:
    build:
      context: ${PWD}/haproxy/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: haproxy
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - kc1
      - kc2
    networks:
      - kc-network
    volumes:
      - haproxy-log:/dev/log

volumes:
  db-data:
  kc-log:
  haproxy-log:

networks:
  kc-network:

