version: "3.8"

services:
  db:
    image: postgres:15-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5455:5432
    networks:
      - kc-network

  kc1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kc1
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - kc-network
    ports:
      - 9091:8080
    volumes:
      - ${PWD}/kc1-logs:/var/log/keycloak
      - ${PWD}/kc1-data:/data/keycloak

  kc2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kc2
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - kc-network
    ports:
      - 9092:8080
    volumes:
      - ${PWD}/kc2-logs:/var/log/keycloak
      - ${PWD}/kc2-data:/data/keycloak

  haproxy:
    image: haproxy:lts-bookworm
    restart: unless-stopped
    container_name: haproxy
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/haproxy.cfg:/etc/haproxy/conf.d/haproxy.cfg:ro
    depends_on:
      - kc1
      - kc2
    networks:
      - kc-network

volumes:
  db-data:
  kc1-logs:
  kc2-logs:
  kc1-data:
  kc2-data:

networks:
  kc-network:
