version: "3.8"

services:
  db:
    image: postgres:15-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5455:5432
    networks:
      - kc-network

  kc1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - kc-network
    volumes:
      - ${PWD}/kc-logs:/var/log/keycloak

  kc2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - kc-network
    volumes:
      - ${PWD}/kc-logs:/var/log/keycloak

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kc1
      - kc2
    networks:
      - kc-network

volumes:
  db-data:

networks:
  kc-network:
  kc-logs:
